# ==============================
# BASE DE DATOS - MySQL local
# ==============================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/playpdf?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:PracticaRoot}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================
# JWT
# ==============================
jwt.secret=${JWT_SECRET:+5BZ%{dn<FLXAzb(x)/H[CJqL|y)]JQ?U6%YD^8RY.Z}
jwt.expiration=86400000

# ==============================
# ALMACENAMIENTO DE PDFs
# ==============================
almacenamiento.directorio-pdfs=${ALMACENAMIENTO_DIRECTORIO_PDFS:./pdfs-subidos}

# ==============================
# CORS - URL del frontend Vue
# ==============================
frontend.url=${FRONTEND_URL:http://localhost:5173}

# ==============================
# TAMAÑO MÁXIMO DE ARCHIVOS
# ==============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ==============================
# IA - Groq
# ==============================
ia.api-key=${IA_API_KEY:}
ia.modelo=${IA_MODELO:llama-3.3-70b-versatile}
ia.url=${IA_URL:https://api.groq.com/openai/v1/chat/completions}

# ==============================
# CÓDIGO DE ACCESO para roles
# ==============================
registro.codigo-profesor=PROF2026
registro.codigo-admin=ADMIN2026

server.port=8080
