# ==============================
# BASE DE DATOS - MySQL local
# ==============================
spring.datasource.url=jdbc:mysql://localhost:3306/playpdf?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=PracticaRoot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==============================
# JWT
# ==============================
jwt.secret=playpdf_clave_secreta_muy_larga_y_segura_2024_cambiar_en_produccion
jwt.expiration=86400000

# ==============================
# ALMACENAMIENTO DE PDFs
# ==============================
almacenamiento.directorio-pdfs=./pdfs-subidos

# ==============================
# CORS - URL del frontend Vue
# ==============================
frontend.url=http://localhost:5173

# ==============================
# TAMAÑO MÁXIMO DE ARCHIVOS
# ==============================
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# ==============================
# IA - API Key (OpenAI u otro)
# Cambia por tu clave real
# ==============================
ia.api-key=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
ia.modelo=llama-3.3-70b-versatile
ia.url=https://api.groq.com/openai/v1/chat/completions

# ==============================
# CÓDIGO DE ACCESO para roles
# ==============================
registro.codigo-profesor=PROF2026
registro.codigo-admin=ADMIN2026

server.port=8080
